config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    get "/" => "homes#top"
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_items, only: [:update]
  end

  scope module: :public do
    root 'homes#top'
    get '/about' => 'homes#about'
    resources :items, only: [:index, :show]
    resource :customers, only: [:show, :edit, :update]
    get '/customers/unsubscribe' => 'customers#unsubscribe'
    patch '/customers/withdrawal' => 'customers#withdrawal'
    delete '/cart_items/delete_all' => 'cart_items#delete_all'
    delete '/cart_items/:id' => 'cart_items#delete'
    resources :cart_items, only: [:index, :update, :delete, :create]
    get '/orders/thanks' => 'orders#thanks'
    post '/orders/confirm' => 'orders#confirm'
    resources :orders, only: [:new, :create, :index, :show]
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  end

  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :email, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true

  def full_address
    self.current_customer.postal_code + self.current_customer.address + self.current_customer.name
  end

  def full_name
    self.last_name + self.first_name
  end

  def active_for_authentication?
    super && (self.is_active == true)
  end

  def update_without_current_password(params, *options)
    params.delete(:current_password)
    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end
    result = update_attributes(params, *options)
    clean_up_passwords
    result
  end

  
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!
  def index
    @customers = Customer.all.page(params[:page]).per(10)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admin_customer_path
    else
      render :edit
    end
  end
  
  private
   def customer_params
     params.require(:customer).permit(
       :first_name,:last_name,:first_name_kana,:last_name_kana,:postal_code,:address,:telephone_number,:email,:is_active)
   end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<h4 class="m-5 w-25 bg-light text-center">
  <%= @customer.last_name %>
  <%= @customer.first_name %>
  さんの会員情報編集
</h4>
<br>
<div class="container">
  <div class="row">
    <div class="col-lg-10">
      <% if @customer.errors.any? %>
      <%= @customer.errors.count %>件のエラーが発生しました
      <ul>
        <% @customer.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
      <%= form_with model: @customer, url: admin_customer_path, local:true do |f| %>
        <table class="table">
          <tr>
            <th class="text-left">会員ID</th>
            <td><%= @customer.id %></td>
          </tr>
          <tr>
            <th class="text-left">氏名</th>
            <td>
              <%= f.text_field :last_name %>
              <%= f.text_field :first_name %>
            </td>
          </tr>
          <tr>
            <th class="text-left">フリガナ</th>
            <td>
              <%= f.text_field :last_name_kana %>
              <%= f.text_field :first_name_kana %>
            </td>
          </tr>
          <tr>
            <th class="text-left">郵便番号</th>
            <td><%= f.text_field :postal_code %></td>
          </tr>
          <tr>
            <th class="text-left">住所</th>
            <td><%= f.text_field :address, size: 42 %></td>
          </tr>
          <tr>
            <th class="text-left">電話番号</th>
            <td><%= f.text_field :telephone_number %></td>
          </tr>
          <tr>
            <th class="text-left">メールアドレス</th>
            <td><%= f.text_field :email %></td>
          </tr>
          <tr>
            <th class="text-left">会員ステータス</th>
            <td>
              <%= f.radio_button :is_active, true %>
              <%= f.label :is_active, "有効" %>
              <%= f.radio_button :is_active, false %>
              <%= f.label :is_active, "退会" %>
            </td>
          </tr>
          <tr>
            <div class="form-action">
              <th><%= f.submit "変更を保存", class:"btn btn-success" %></th>
            </div>
          </tr>
        </table>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/customers/index.html.erb
<h4 class="m-5 w-25 bg-light text-center">会員一覧</h4>
<br>
<div class="container">
  <div class="row">
    <div class="col-lg-10">
      <table class="table">
        <thead class="thead-light">
          <tr>
            <th>会員ID</th>
            <th>氏名</th>
            <th>メールアドレス</th>
            <th>ステータス</th>
          </tr>
          <tbody>
            <% @customers.each do |customer| %>
              <tr>
                <td class="aline-middle">
                  <%= customer.id %>
                </td>
                <td class="aline-middle">
                  <%= link_to customer.full_name, admin_customer_path(customer) %>
                </td>
                <td class="aline-middle">
                  <%= customer.email %>
                </td>
                <td class="aline-middle">
                  <% if customer.is_active == false %>
                    <p class="text-secondary">退会</p>
                  <% else %>
                    <p class="text-success">有効</p>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </thead>
      </table>
    </div>
  </div>
  <div class="d-flex justify-content-center"><%= paginate(@customers)%></div>
</div>

app/views/admin/customers/show.html.erb
<h4 class="m-5 w-25 bg-light text-center">
  <%= @customer.last_name %>
  <%= @customer.first_name %>
  さんの会員詳細
</h4>
<br>
<div class="container">
  <div class="row">
    <div class="col-lg-10">
      <table class="table">
        <tr>
          <th class="text-left">会員ID</th>
          <td>
            <%= @customer.id %>
          </td>
        </tr>
        <tr>
          <th class="text-left">氏名</th>
          <td>
            <%= @customer.last_name %>
            <%= @customer.first_name %>
          </td>
        </tr>
        <tr>
        <th class="text-left">フリガナ</th>
          <td>
            <%= @customer.last_name_kana %>
            <%= @customer.first_name_kana %>
          </td>
        </tr>
        <tr>
          <th class="text-left">郵便番号</th>
          <td>
            <%= @customer.postal_code %>
          </td>
        </tr>
        <tr>
          <th class="text-left">住所</th>
          <td>
            <%= @customer.address %>
          </td>
        </tr>
        <tr>
          <th class="text-left">電話番号</th>
          <td>
            <%= @customer.telephone_number %>
          </td>
        </tr>
        <tr>
          <th class="text-left">メールアドレス</th>
          <td>
            <%= @customer.email %>
          </td>
        </tr>
        <tr>
          <th class="text-left">会員ステータス</th>
          <% if @customer.is_active == false %>
            <td class="text-secondary">退会</td>
          <% else %>
            <td class="text-success">有効</td>
          <% end %>
        </tr>
      </table>
      <div class="d-flex justify-content-center">
        <p><%= link_to "編集する",edit_admin_customer_path, class:"btn btn-success"%></p>&ensp;&ensp;
        <p><%= link_to "注文履歴一覧を見る",admin_path, class:"btn btn-primary"%></p>
      </div>
    </div>
  </div>
</div>

app/views/admin/customers/update.html.erb
<h1>Admin::Customers#update</h1>
<p>Find me in app/views/admin/customers/update.html.erb</p>