config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    get "/" => "homes#top"
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_items, only: [:update]
  end

  scope module: :public do
    root 'homes#top'
    get '/about' => 'homes#about'
    resources :items, only: [:index, :show]
    resource :customers, only: [:show, :edit, :update]
    get '/customers/unsubscribe' => 'customers#unsubscribe'
    patch '/customers/withdrawal' => 'customers#withdrawal'
    delete '/cart_items/delete_all' => 'cart_items#delete_all'
    delete '/cart_items/:id' => 'cart_items#delete'
    resources :cart_items, only: [:index, :update, :delete, :create]
    get '/orders/thanks' => 'orders#thanks'
    post '/orders/confirm' => 'orders#confirm'
    resources :orders, only: [:new, :create, :index, :show]
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  end

  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  
  validates :customer_id, :name, :address, presence: true
  validates :postal_code, length: {is: 7}, numericality: { only_integer: true }

  def full_address
    "〒" + self.postal_code + " " + self.address + " " + self.name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item

  validates :amount, numericality: { only_integer: true }
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :email, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true

  def full_address
    self.current_customer.postal_code + self.current_customer.address + self.current_customer.name
  end

  def full_name
    self.last_name + self.first_name
  end

  def active_for_authentication?
    super && (self.is_active == true)
  end

  def update_without_current_password(params, *options)
    params.delete(:current_password)
    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end
    result = update_attributes(params, *options)
    clean_up_passwords
    result
  end

  
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
  validates :name, presence: true
  
end

app/models/item.rb
class Item < ApplicationRecord
  attachment :image
  has_many :cart_items, dependent: :destroy
  has_many :order_items
  belongs_to :genre

  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true
  validates :image, presence: true
  validates :genre_id, presence: true

  def with_tax_price
    (price * 1.1).floor
  end

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_items, dependent: :destroy
  has_many :items

  validates :customer_id, :address, :name, :shipping_fee,
            :payment_method, presence: true
  validates :postal_code, length: {is: 7}, numericality: { only_integer: true }


  def with_tax_price(cart_item)
    (price * 1.1).floor
  end

  enum payment_method: { クレジットカード: 0, 銀行振込: 1 }
  enum order_status: { 入金待ち: 0, 入金確認: 1, 製作中: 2, 発送準備中: 3, 発送済み: 4 }

  def shipping_fee
   self.shipping_fee = 800
  end

end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :item
  
  validates :item_id, :order_id, :amount, :ordered_price, presence: true
  validates :ordered_price, :amount, numericality: { only_integer: true }

  enum making_status: { 着手不可: 0, 製作待ち: 1, 製作中: 2, 製作完了: 3 }

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!
  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path, notice: "新しいジャンルを追加しました"
    else
      @genres = Genre.all
      render :index
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path
    else
      render 'edit'
    end
  end

  private
  
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  def top
    @params = params[:id]
    @order = Order.where(customer_id: @params).page(params[:page]).per(10).order(created_at: :desc)
    @orders = Order.page(params[:page]).per(10).order(created_at: :desc)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  def index
    @items = Item.page(params[:page]).per(10)
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item)
    else
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item)
    else
      render :edit
    end
  end

  private
  def item_params
    params.require(:item).permit(:image, :name, :introduction, :genre_id, :price, :is_active)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base



end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_items_helper.rb
module Admin::OrderItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_name(customer)
    customer.last_name + customer.first_name
  end

  def sub_price(sub)
    sub.item.with_tax_price * sub.amount
  end

  def total_price(totals)
    price = 0
    totals.each do |total|
      price += sub_price(total)
    end
    return price
  end

end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header class="shadow-sm">
    <nav class="navbar navbar-expand-lg navbar-light">
      <div class="container">
        <a class="navbar-brand p-3" href="/">logo</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                      aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
          <% if customer_signed_in? %>
          <li class="nav-item">
            <%= link_to "マイページ", customers_path, class: 'btn btn-outline-dark' %>&ensp;&ensp;
          </li>
          <li class="nav-item">
            <%= link_to "商品一覧", items_path, class: 'btn btn-outline-dark' %>&ensp;&ensp;
          </li>
          <li class="nav-item">
            <%= link_to "カート", cart_items_path, class: 'btn btn-outline-dark' %>&ensp;&ensp;
          </li>
          <li class="nav-item">
            <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: 'btn btn-outline-dark' %>&ensp;&ensp;
          </li>
          <% elsif admin_signed_in? %>
          <li class="nav-item">
            <%= link_to "商品一覧", admin_items_path, class: 'btn btn-outline-dark' %>&ensp;&ensp;
          </li>
          <li class="nav-item">
            <%= link_to "会員一覧", admin_customers_path, class: 'btn btn-outline-dark' %>&ensp;&ensp;
          </li>
          <li class="nav-item">
            <%= link_to "注文履歴一覧", admin_path, class: 'btn btn-outline-dark' %>&ensp;&ensp;
          </li>
          <li class="nav-item">
            <%= link_to "ジャンル一覧", admin_genres_path, class: 'btn btn-outline-dark' %>&ensp;&ensp;
          </li>
          <li class="nav-item">
            <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'btn btn-outline-dark' %>&ensp;&ensp;
          </li>
          <% else %>
          <li class="nav-item">
            <%= link_to "About", about_path, class: 'btn btn-outline-dark' %>&ensp;&ensp;
          </li>
          <li class="nav-item">
            <%= link_to "商品一覧", items_path, class: 'btn btn-outline-dark' %>&ensp;&ensp;
          </li>
          <li class="nav-item">
            <%= link_to "新規登録", new_customer_registration_path, class: 'btn btn-outline-dark' %>&ensp;&ensp;
          </li>
          <li class="nav-item">
            <%= link_to "ログイン", new_customer_session_path, class: 'btn btn-outline-dark'%>
          </li>
          <% end %>
          </ul>
        </div>
      </div>
    </nav>
  </header>
    <%= yield %>
  </body>
</html>